name: License Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Cancel already running jobs
concurrency:
  group: license_check_${{ github.head_ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  license_check:
    runs-on: ubuntu-22.04
    name: License Check
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - name: cargo deny
        run: |
          wget https://github.com/EmbarkStudios/cargo-deny/releases/download/0.13.9/cargo-deny-0.13.9-x86_64-unknown-linux-musl.tar.gz -O cargo-deny.tar.gz
          tar -xvf cargo-deny.tar.gz
          ./cargo-deny-0.13.9-x86_64-unknown-linux-musl/cargo-deny check licenses
